### ISSUE TITLE
 The ADFA Intrusion Detection Datasets Page not found

### ISSUE THREAD

**Issue by SaidaniMohamed** [gfek/Real-CyberSecurity-Datasets#1]
Hi! Page not found for The ADFA Intrusion Detection Datasets can you plz double check!

**Comment by gfek** [comment]
Hi. Thank you for your comment. For some reason the page cannot be found (in the google cache you can find it, however the data are not there any more). The day before yesterday the page was there. I will remove it from the list. I will check it again in the future.
